CXX = g++
CXXFLAGS = -std=c++11 -Wall -Iinclude
SRC = src/main.cpp src/file_handler.cpp src/grade_calculator.cpp
OUT = ../../../build/student_management

all:
	$(CXX) $(CXXFLAGS) $(SRC) -o $(OUT)

clean:
	rm -f $(OUT)
